### ISSUE TITLE
Repo cannot sync

### ISSUE THREAD

**Issue by minmemory** [FlymeOS/manifest#1]
[root@Yvonne flyme]# repo init -u https://github.com/FlymeOS/manifest.git -b lollipop-5.0
gpg: keyring `/root/.repoconfig/gnupg/secring.gpg' created
gpg: keyring`/root/.repoconfig/gnupg/pubring.gpg' created
gpg: /root/.repoconfig/gnupg/trustdb.gpg: trustdb created
gpg: key 920F5C65: public key "Repo Maintainer repo@android.kernel.org" imported
gpg: Total number processed: 1
gpg:               imported: 1

Getting repo ...
   from git://codeaurora.org/tools/repo.git
remote: Counting objects: 3090, done.
remote: Compressing objects: 100% (954/954), done.
remote: Total 3090 (delta 2082), reused 3090 (delta 2082)
Receiving objects: 100% (3090/3090), 678.31 KiB | 492 KiB/s, done.
Resolving deltas: 100% (2082/2082), done.
From git://codeaurora.org/tools/repo
- [new branch]      aosp-new/maint -> origin/aosp-new/maint
- [new branch]      aosp-new/master -> origin/aosp-new/master
- [new branch]      aosp-new/stable -> origin/aosp-new/stable
- [new branch]      caf-stable -> origin/caf-stable
- [new branch]      master     -> origin/master
- [new branch]      stable     -> origin/stable
- [new tag]         v1.10.4    -> v1.10.4
- [new tag]         v1.12.16   -> v1.12.16
- [new tag]         v1.12.22   -> v1.12.22
- [new tag]         v1.6.8.1   -> v1.6.8.1
- [new tag]         v1.7.5     -> v1.7.5
  remote: Counting objects: 118, done.
  remote: Compressing objects: 100% (118/118), done.
  remote: Total 118 (delta 0), reused 118 (delta 0)
  Receiving objects: 100% (118/118), 36.22 KiB, done.
  From git://codeaurora.org/tools/repo
- [new tag]         v1.0       -> v1.0
- [new tag]         v1.0.1     -> v1.0.1
- [new tag]         v1.0.2     -> v1.0.2
- [new tag]         v1.0.3     -> v1.0.3
- [new tag]         v1.0.4     -> v1.0.4
- [new tag]         v1.0.5     -> v1.0.5
- [new tag]         v1.0.6     -> v1.0.6
- [new tag]         v1.0.7     -> v1.0.7
- [new tag]         v1.0.8     -> v1.0.8
- [new tag]         v1.0.9     -> v1.0.9
- [new tag]         v1.1       -> v1.1
- [new tag]         v1.10.0    -> v1.10.0
- [new tag]         v1.10.1    -> v1.10.1
- [new tag]         v1.10.2    -> v1.10.2
- [new tag]         v1.10.3    -> v1.10.3
- [new tag]         v1.11.0    -> v1.11.0
- [new tag]         v1.11.1    -> v1.11.1
- [new tag]         v1.12.0    -> v1.12.0
- [new tag]         v1.12.1    -> v1.12.1
- [new tag]         v1.12.10   -> v1.12.10
- [new tag]         v1.12.11   -> v1.12.11
- [new tag]         v1.12.12   -> v1.12.12
- [new tag]         v1.12.13   -> v1.12.13
- [new tag]         v1.12.14   -> v1.12.14
- [new tag]         v1.12.15   -> v1.12.15
- [new tag]         v1.12.17   -> v1.12.17
- [new tag]         v1.12.18   -> v1.12.18
- [new tag]         v1.12.19   -> v1.12.19
- [new tag]         v1.12.2    -> v1.12.2
- [new tag]         v1.12.20   -> v1.12.20
- [new tag]         v1.12.21   -> v1.12.21
- [new tag]         v1.12.3    -> v1.12.3
- [new tag]         v1.12.3.1  -> v1.12.3.1
- [new tag]         v1.12.4    -> v1.12.4
- [new tag]         v1.12.5    -> v1.12.5
- [new tag]         v1.12.6    -> v1.12.6
- [new tag]         v1.12.7    -> v1.12.7
- [new tag]         v1.12.8    -> v1.12.8
- [new tag]         v1.12.9    -> v1.12.9
- [new tag]         v1.2       -> v1.2
- [new tag]         v1.3       -> v1.3
- [new tag]         v1.3.1     -> v1.3.1
- [new tag]         v1.3.2     -> v1.3.2
- [new tag]         v1.4       -> v1.4
- [new tag]         v1.4.1     -> v1.4.1
- [new tag]         v1.4.2     -> v1.4.2
- [new tag]         v1.4.3     -> v1.4.3
- [new tag]         v1.4.4     -> v1.4.4
- [new tag]         v1.5       -> v1.5
- [new tag]         v1.5.1     -> v1.5.1
- [new tag]         v1.6       -> v1.6
- [new tag]         v1.6.1     -> v1.6.1
- [new tag]         v1.6.10    -> v1.6.10
- [new tag]         v1.6.10.1  -> v1.6.10.1
- [new tag]         v1.6.10.2  -> v1.6.10.2
- [new tag]         v1.6.2     -> v1.6.2
- [new tag]         v1.6.3     -> v1.6.3
- [new tag]         v1.6.4     -> v1.6.4
- [new tag]         v1.6.5     -> v1.6.5
- [new tag]         v1.6.6     -> v1.6.6
- [new tag]         v1.6.7     -> v1.6.7
- [new tag]         v1.6.7.1   -> v1.6.7.1
- [new tag]         v1.6.7.2   -> v1.6.7.2
- [new tag]         v1.6.7.3   -> v1.6.7.3
- [new tag]         v1.6.7.4   -> v1.6.7.4
- [new tag]         v1.6.7.5   -> v1.6.7.5
- [new tag]         v1.6.8     -> v1.6.8
- [new tag]         v1.6.8.10  -> v1.6.8.10
- [new tag]         v1.6.8.11  -> v1.6.8.11
- [new tag]         v1.6.8.2   -> v1.6.8.2
- [new tag]         v1.6.8.3   -> v1.6.8.3
- [new tag]         v1.6.8.4   -> v1.6.8.4
- [new tag]         v1.6.8.5   -> v1.6.8.5
- [new tag]         v1.6.8.6   -> v1.6.8.6
- [new tag]         v1.6.8.7   -> v1.6.8.7
- [new tag]         v1.6.8.8   -> v1.6.8.8
- [new tag]         v1.6.8.9   -> v1.6.8.9
- [new tag]         v1.6.9     -> v1.6.9
- [new tag]         v1.6.9.1   -> v1.6.9.1
- [new tag]         v1.6.9.2   -> v1.6.9.2
- [new tag]         v1.6.9.3   -> v1.6.9.3
- [new tag]         v1.6.9.4   -> v1.6.9.4
- [new tag]         v1.6.9.5   -> v1.6.9.5
- [new tag]         v1.6.9.6   -> v1.6.9.6
- [new tag]         v1.6.9.7   -> v1.6.9.7
- [new tag]         v1.6.9.8   -> v1.6.9.8
- [new tag]         v1.7       -> v1.7
- [new tag]         v1.7.1     -> v1.7.1
- [new tag]         v1.7.2     -> v1.7.2
- [new tag]         v1.7.3     -> v1.7.3
- [new tag]         v1.7.3.1   -> v1.7.3.1
- [new tag]         v1.7.4     -> v1.7.4
- [new tag]         v1.7.4.1   -> v1.7.4.1
- [new tag]         v1.7.4.2   -> v1.7.4.2
- [new tag]         v1.7.4.3   -> v1.7.4.3
- [new tag]         v1.7.6     -> v1.7.6
- [new tag]         v1.7.6.1   -> v1.7.6.1
- [new tag]         v1.7.7     -> v1.7.7
- [new tag]         v1.7.7.1   -> v1.7.7.1
- [new tag]         v1.7.7.2   -> v1.7.7.2
- [new tag]         v1.7.7.3   -> v1.7.7.3
- [new tag]         v1.7.7.4   -> v1.7.7.4
- [new tag]         v1.7.7.5   -> v1.7.7.5
- [new tag]         v1.7.7.6   -> v1.7.7.6
- [new tag]         v1.7.8     -> v1.7.8
- [new tag]         v1.7.8.1   -> v1.7.8.1
- [new tag]         v1.7.8.2   -> v1.7.8.2
- [new tag]         v1.8.0     -> v1.8.0
- [new tag]         v1.8.1     -> v1.8.1
- [new tag]         v1.8.2     -> v1.8.2
- [new tag]         v1.9.0     -> v1.9.0
- [new tag]         v1.9.1     -> v1.9.1
- [new tag]         v1.9.2     -> v1.9.2
- [new tag]         v1.9.3     -> v1.9.3
- [new tag]         v1.9.4     -> v1.9.4
- [new tag]         v1.9.5     -> v1.9.5
- [new tag]         v1.9.6     -> v1.9.6
  Getting manifest ...
  from https://github.com/FlymeOS/manifest.git
  remote: Counting objects: 10, done.
  remote: Compressing objects: 100% (8/8), done.
  remote: Total 10 (delta 2), reused 10 (delta 2), pack-reused 0
  Unpacking objects: 100% (10/10), done.
  From https://github.com/FlymeOS/manifest
- [new branch]      lollipop-5.0 -> origin/lollipop-5.0

Your Name  [root]: Yvonne Lu
Your Email [root@Athena.utb.cc]: min@utbhost.com

Your identity is: Yvonne Lu min@utbhost.com
is this correct [y/n]? y

Testing colorized output (for 'repo diff', 'repo status'):
  black    red      green    yellow   blue     magenta   cyan     white 
  bold     dim      ul       reverse 
Enable color display in this user account (y/n)? y

repo initialized in /root/flyme
[root@Yvonne flyme]# repo sync
fatal: '../FlymeOS/build.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
error: Cannot fetch FlymeOS/build

**Comment by duanqz** [comment]
清一下gpg吧
