### ISSUE TITLE
flymed二进制平台问题

### ISSUE THREAD

**Issue by qiurigao** [FlymeOS/manifest#11]
`android:/system/bin $ flymed
/system/bin/sh: /system/bin/flymed: not executable: 64-bit ELF file
`
我的手机是arm平台，不支持arm64，插桩工具会自动识别吗？还是需要在哪定义
二进制文件不对唉

**Comment by qiurigao** [comment]
```
W dex2oat : Verification failed on class android.widget.PopupWindow in /system/framework/framework.jar:classes2.dex because: Verifier rejected class android.widget.PopupWindow due to bad method boolean android.widget.PopupWindow.findDropDownPosition(android.view.View, android.view.WindowManager$LayoutParams, int, int, int)
06-05 15:09:08.170   996  1518 W dex2oat : Rejecting class android.widget.Editor$ErrorPopup that attempts to sub-class erroneous class android.widget.PopupWindow in /system/framework/framework.jar:classes2.dex
06-05 15:09:08.170   996  1519 W dex2oat : Rejecting class android.widget.Editor$SuggestionsPopupWindow$CustomPopupWindow that attempts to sub-class erroneous class android.widget.PopupWindow in /system/framework/framework.jar:classes2.dex

```
这个系统似乎带有dex2oat验证，无法启动？

**Comment by hexiaoshuai** [comment]
第一个问题半个月前已经更新了32位的bin make clean-all 再make就可以了
第二个问题是提示这个类中有个错误的方法

**Comment by qiurigao** [comment]
@hexiaoshuai  我发现生成的刷机包中没有boot.art 和boot.oat文件。系统一直提示dex2oat无法加载。不能生成吗？
这是我原版系统的目录
`flyme@flyme-Build:~/桌面/superr/superr_otaimg/system/framework$` ll arm oat/arm
arm:
总用量 73996
drwxr-xr-x. 2 root root     4096 1月   1  2009 ./
drwxr-xr-x. 4 root root     4096 1月   1  2009 ../
-rw-r--r--. 1 root root 11579392 1月   1  2009 boot.art
-rw-r--r--. 1 root root 64180716 1月   1  2009 boot.oat

oat/arm:
总用量 28556
drwxr-xr-x. 2 root root     4096 1月   1  2009 ./
drwxr-xr-x. 3 root root     4096 1月   1  2009 ../
-rw-r--r--. 1 root root   156140 1月   1  2009 am.odex
-rw-r--r--. 1 root root   393708 1月   1  2009 android.test.runner.odex
-rw-r--r--. 1 root root    29164 1月   1  2009 appops.odex
-rw-r--r--. 1 root root    16876 1月   1  2009 appwidget.odex
-rw-r--r--. 1 root root    41452 1月   1  2009 bmgr.odex
-rw-r--r--. 1 root root    25068 1月   1  2009 btmultisimlibrary.odex
-rw-r--r--. 1 root root    16876 1月   1  2009 bu.odex
-rw-r--r--. 1 root root    16876 1月   1  2009 com.android.future.usb.accessory.odex
-rw-r--r--. 1 root root    61932 1月   1  2009 com.android.location.provider.odex
-rw-r--r--. 1 root root    12780 1月   1  2009 com.android.mediadrm.signer.odex
-rw-r--r--. 1 root root    25068 1月   1  2009 com.android.media.remotedisplay.odex
-rw-r--r--. 1 root root    29164 1月   1  2009 com.android.nfc_extras.odex
-rw-r--r--. 1 root root    12780 1月   1  2009 com.google.widevine.software.drm.odex
-rw-r--r--. 1 root root   106988 1月   1  2009 com.qualcomm.location.vzw_library.odex
-rw-r--r--. 1 root root    49644 1月   1  2009 content.odex
-rw-r--r--. 1 root root    16876 1月   1  2009 dpm.odex
-rw-r--r--. 1 root root    53740 1月   1  2009 ethernet-service.odex
-rw-r--r--. 1 root root    41452 1月   1  2009 hid.odex
-rw-r--r--. 1 root root    25068 1月   1  2009 ime.odex
-rw-r--r--. 1 root root    25068 1月   1  2009 input.odex
-rw-r--r--. 1 root root   164332 1月   1  2009 javax.obex.odex
-rw-r--r--. 1 root root    33260 1月   1  2009 media_cmd.odex
-rw-r--r--. 1 root root   287212 1月   1  2009 monkey.odex
-rw-r--r--. 1 root root     8684 1月   1  2009 org.codeaurora.camera.odex
-rw-r--r--. 1 root root    94700 1月   1  2009 org.simalliance.openmobileapi.odex
-rw-r--r--. 1 root root   147948 1月   1  2009 pm.odex
-rw-r--r--. 1 root root   373228 1月   1  2009 qcrilhook.odex
-rw-r--r--. 1 root root    20972 1月   1  2009 QPerformance.odex
-rw-r--r--. 1 root root   684524 1月   1  2009 qti-telephony-common.odex
-rw-r--r--. 1 root root   119276 1月   1  2009 QtiTelephonyServicelibrary.odex
-rw-r--r--. 1 root root    33260 1月   1  2009 requestsync.odex
-rw-r--r--. 1 root root 19554796 1月   1  2009 services.odex
-rw-r--r--. 1 root root    29164 1月   1  2009 settings.odex
-rw-r--r--. 1 root root    25068 1月   1  2009 sm.odex
-rw-r--r--. 1 root root    33260 1月   1  2009 svc.odex
-rw-r--r--. 1 root root    25068 1月   1  2009 telecom.odex
-rw-r--r--. 1 root root   270828 1月   1  2009 uiautomator.odex
-rw-r--r--. 1 root root  6005228 1月   1  2009 wifi-service.odex
-rw-r--r--. 1 root root    25068 1月   1  2009 wm.odex
但是插桩后这两个目录都被合并没有啦，可否让生成的包不合并dex？

**Comment by hexiaoshuai** [comment]
dex2oat校验的是class文件并非是校验有没有boot.oat

**Comment by qiurigao** [comment]
能否开启oat编译？
