### ISSUE TITLE
[Solved] flyme newproject

### ISSUE THREAD

**Issue by aymende7** [FlymeOS/manifest#12]
/system/: 1424 files pulled. 2.4 MB/s (422806151 bytes in 165.229s)
>>> pullSpecialSelabelFile with su-pull ...
Set /system/bin/app_process32 to be readable
unknown option -- o
Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
usage: chmod [-R] MODE FILE...

Change mode of listed file[s] (recursively with -R).

MODE can be (comma-separated) stanzas: [ugoa][+-=][rwxstXugo]

Stanzas are applied in order: For each category (u = user,
g = group, o = other, a = all three, if none specified default is a),
set (+), clear (-), or copy (=), r = read, w = write, x = execute.
s = u+s = suid, g+s = sgid, o+s = sticky. (+t is an alias for o+s).
suid/sgid: execute as the user/group who owns the file.
sticky: can't delete files you don't own out of this directory
X = x for directories or if any category already has x set.

Or MODE can be an octal value up to 7777	ug uuugggooo	top +
bit 1 = o+x, bit 1<<8 = u+w, 1<<11 = g+1	sstrwxrwxrwx	bottom

Examples:
chmod u+w file - allow owner of "file" to write to it.
chmod 744 file - user can read/write/execute, everyone else read only

chmod: Need 2 arguments
[100%] /data/local/tmp/phone-check-su
/home/aymen/bin/tools/su-tools/phone-check-su: 1 file pushed. 0.0 MB/s (115 bytes in 0.003s)
su is ok
[100%] /data/local/tmp/phone-cp
/home/aymen/bin/tools/su-tools/phone-cp: 1 file pushed. 0.0 MB/s (414 bytes in 0.033s)
begin copy /system/bin/app_process32 to /data/local/tmp/su_pull_tmp/app_process32
unknown option -- r
Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
Unknown id: /data/local/tmp/su_pull_tmp
usage: chmod [-R] MODE FILE...

Change mode of listed file[s] (recursively with -R).

MODE can be (comma-separated) stanzas: [ugoa][+-=][rwxstXugo]

Stanzas are applied in order: For each category (u = user,
g = group, o = other, a = all three, if none specified default is a),
set (+), clear (-), or copy (=), r = read, w = write, x = execute.
s = u+s = suid, g+s = sgid, o+s = sticky. (+t is an alias for o+s).
suid/sgid: execute as the user/group who owns the file.
sticky: can't delete files you don't own out of this directory
X = x for directories or if any category already has x set.

Or MODE can be an octal value up to 7777	ug uuugggooo	top +
bit 1 = o+x, bit 1<<8 = u+w, 1<<11 = g+1	sstrwxrwxrwx	bottom

Examples:
chmod u+w file - allow owner of "file" to write to it.
chmod 744 file - user can read/write/execute, everyone else read only

chmod: Need 2 arguments
Unknown id: /system/bin/app_process32
unknown option -- R
Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
adb: error: cannot create file/directory '/home/aymen/bin/devices/s2_plus/out/oem_target_files/SYSTEM/bin/app_process32': No such file or directory
unknown option -- r
Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
<<< pullSpecialSelabelFile with su-pull done
>>> pullFailedFailes again with su-pull ...
<<< pullFailedFailes again with su-pull done
<< retrieve whole /system from device (time-costly, be patient) done
>> prepare boot.img and recovery.img ...
>>> Copy boot.img to /home/aymen/bin/devices/s2_plus/out/oem_target_files/BOOTABLE_IMAGES/boot.img
>>> Copy recovery.fstab to /home/aymen/bin/devices/s2_plus/out/oem_target_files/RECOVERY/RAMDISK/etc/recovery.fstab
<< prepare boot.img and recovery.img done
>> zip /home/aymen/bin/devices/s2_plus/out/oem_target_files.zip from /home/aymen/bin/devices/s2_plus/out/oem_target_files ...
/home/aymen/bin/devices/s2_plus
<< zip /home/aymen/bin/devices/s2_plus/out/oem_target_files.zip from /home/aymen/bin/devices/s2_plus/out/oem_target_files done
<<< generate vendor target files done
>>> normalize the out/oem_target_files.zip ...
D/reverse: Program args = []
I/reverse-zipformatter: unzip /home/aymen/bin/devices/s2_plus/out/oem_target_files.zip to /tmp/tmpazOVe6
D/reverse-zipformatter: 
I/reverse-zipformatter: process(): Creating None ZipFormatter...
Traceback (most recent call last):
  File "/home/aymen/bin/tools/otanormalize", line 38, in <module>
    ZipFormatter.create(OPTIONS).format()
  File "/home/aymen/bin/tools/reverses/zipformatter.py", line 96, in create
    raise Exception("Unknown OTA package zip. Is it an ART or DALVIKVM package?")
Exception: Unknown OTA package zip. Is it an ART or DALVIKVM package?
/home/aymen/bin/build/newproject.mk:30: recipe for target 'out/oem_target_files.zip.std.zip' failed
make: *** [out/oem_target_files.zip.std.zip] Error 1

<<< newproject failed

**Comment by hexiaoshuai** [comment]
Your ROOT is incomplete. Please try another ROOT method

**Comment by aymende7** [comment]
Thanks for replying
![screenshot_20170606-191443](https://user-images.githubusercontent.com/25817880/26847427-8c123ed0-4aec-11e7-9c55-c3aca0afc1e4.png)
i tired kingroot same problem
i am using aosp 6.0.1 as base
linuxmint 18.1 64bit
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
Python 2.7.12 
Edit : Cyanogenmod 13 same problem :/

**Comment by aymende7** [comment]
Python 2.7.12

**Comment by hexiaoshuai** [comment]
:-)
