### ISSUE TITLE
Flyme Bootloop

### ISSUE THREAD

**Issue by aymende7** [FlymeOS/manifest#13]
>>> build |target-files|SYSTEM|vendor_modify_jar| to out/obj/system/framework/framework.jar ...
>>>> copy board packages: "flyme meizu com/flyme com/meizu"
 		from /home/aymen/bin/devices/cm/board/system/framework/framework.jar to 
I: Using Apktool 2.1.1-04d478-SNAPSHOT on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
>>>> modify resource id: out/obj/system/framework/framework.board.61E/smali ...
<<<< modify resource id: out/obj/system/framework/framework.board.61E/smali done
>>>> modify resource id: out/obj/system/framework/framework.board.61E/smali_classes2 ...
<<<< modify resource id: out/obj/system/framework/framework.board.61E/smali_classes2 done
<<<< copy board packages done
>>>> in partSmaliAppend.sh
I: Using Apktool 2.1.1-04d478-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65786
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:329)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1027)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:803)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:252)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:230)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:53)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:364)
	at brut.androlib.Androlib.buildSources(Androlib.java:295)
	at brut.androlib.Androlib.build(Androlib.java:278)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)

/home/aymen/bin/build/main.mk:451: recipe for target 'out/obj/system/framework/framework.jar' failed
make[1]: *** [out/obj/system/framework/framework.jar] Error 161
make[1]: Leaving directory '/home/aymen/bin/devices/cm'
/home/aymen/bin/build/main.mk:34: recipe for target 'ota' failed
make: *** [ota] Error 2

**Comment by hexiaoshuai** [comment]
range: 65786 , a dex/jar max method is 65535,see https://github.com/FlymeOS/devices-base/blob/marshmallow-6.0/custom_jar.sh

**Comment by aymende7** [comment]
Should i run it?

**Comment by aymende7** [comment]
thanks it works but i have another problem
> generate ota.zip from target-files.zip (time-costly, be patient) ...
unzipping target target-files...
unable to load device-specific module; assuming none
using prebuilt recovery.img from BOOTABLE_IMAGES...
building system.img from target-files
creating system.img...
Running:  mkuserimg.sh -s /tmp/targetfiles-cV0HfB/system /tmp/system-1Bsdx0.img ext4 system 1073741824 -T 1230768000 -C /tmp/targetfiles-cV0HfB/META/filesystem_config.txt -B /tmp/tmpR1Fj38 -L system /tmp/targetfiles-cV0HfB/BOOT/RAMDISK/file_contexts
make_ext4fs -s -T 1230768000 -S /tmp/targetfiles-cV0HfB/BOOT/RAMDISK/file_contexts -C /tmp/targetfiles-cV0HfB/META/filesystem_config.txt -B /tmp/tmpR1Fj38 -L system -l 1073741824 -a system /tmp/system-1Bsdx0.img /tmp/targetfiles-cV0HfB/system
error: ext4_allocate_best_fit_partial: failed to allocate 630 blocks, out of space?
loaded 2321 fs_config entries
Creating filesystem with parameters:
    Size: 1073741824
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 4096
    Label: system
    Blocks: 262144
    Block groups: 8
    Reserved block group size: 63
Traceback (most recent call last):
  File "/home/aymen/bin/build/tools/releasetools/ota_from_target_files", line 1734, in <module>
    common.Cleanup()
  File "/home/aymen/bin/build/tools/releasetools/common.py", line 752, in Cleanup
    os.remove(i)
OSError: [Errno 2] No such file or directory: '/tmp/system-1Bsdx0.img'
/home/aymen/bin/build/main.mk:699: recipe for target 'out/flyme_GT-I9105P_Aymende7_6.7.6.5R.zip' failed
make[1]: *** [out/flyme_GT-I9105P_Aymende7_6.7.6.5R.zip] Error 51
make[1]: Leaving directory '/home/aymen/bin/devices/cm'
/home/aymen/bin/build/main.mk:34: recipe for target 'ota' failed
make: *** [ota] Error 2

<<< fullota failed

**Comment by hexiaoshuai** [comment]
error: ext4_allocate_best_fit_partial: failed to allocate 630 blocks, out of space?
check your device  https://github.com/FlymeOS/devices-base/blob/marshmallow-6.0/vendor/META/misc_info.txt system_size is correct

**Comment by aymende7** [comment]
`vendor/META/misc_info.txt`
recovery_api_version=3
fstab_version=2
blocksize=0xffffffff
boot_size=0x2000000
recovery_size=0x2000000
system_size=0x40000000
userdata_size=0x62bbfbe00
cache_size=0x6400000
extfs_sparse_flag=-s
tool_extensions=.
default_system_dev_certificate=build/security/testkey
use_set_metadata=1
multistage_support=1
update_rename_support=1
fs_type=ext4
selinux_fc=out/target/product/angler/root/file_contexts

**Comment by hexiaoshuai** [comment]
your device system size is small
you can remove some app keep system not out of space
or move some app to data custom_targetfiles.sh

**Comment by aymende7** [comment]
thanks a lot :D 
- stuck in bootloop :( after flashing
[logcat.txt](https://github.com/FlymeOS/manifest/files/1065188/logcat.txt)

**Comment by WarrenLobo** [comment]
Runtime error /system/lib/libandroid_runtime.so :(
@aymende7

**Comment by aymende7** [comment]
same problem like miui :'(
i think the problem in the base rom
