### ISSUE TITLE
Flyme 6 适配 patchall 后200多文件 不存在 问题

### ISSUE THREAD

**Issue by ghost** [FlymeOS/manifest#17]
Flyme 6 基于 base 插桩，patchall 后 冲突形式是以 file not found 表示出的，共有200多文件不存在，是不是要把 base 里面的文件换进去？
求解决，十分感谢！

**Comment by hexiaoshuai** [comment]
按照步骤重新来一次,还有问题提供终端日志

**Comment by imhansai** [comment]
@t-hua 一般很少有这么多文件找不到的情况，确定机子是arm的？

**Comment by hexiaoshuai** [comment]
android 6.0 ?

**Comment by ghost** [comment]
是的，Android 6.0，ARM64
:)

**Comment by ghost** [comment]
嗯是的，ARM64，6.0
