### ISSUE TITLE
newproject时产生致命错误

### ISSUE THREAD

**Issue by ghost** [FlymeOS/manifest#18]
拉包后报错：
awk: 致命错误: 无法以读模式打开文件“/home/xiaohua/FlymeOS_Patchrom/devices/demo/FMRadio/apktool.yml”(没有那个文件或目录)
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: overriding recipe for target 'out/obj/system/res/FMRadio.remove'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: ignoring old recipe for target 'out/obj/system/res/FMRadio.remove'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: overriding recipe for target 'out/obj/system/app/FMRadio.signed.apk'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: ignoring old recipe for target 'out/obj/system/app/FMRadio.signed.apk'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: overriding recipe for target 'out/merged_target_files/SYSTEM/app/FMRadio.apk'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: ignoring old recipe for target 'out/merged_target_files/SYSTEM/app/FMRadio.apk'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: overriding recipe for target 'clean-FMRadio'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: ignoring old recipe for target 'clean-FMRadio'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: overriding recipe for target 'FMRadio.phone'
/home/xiaohua/FlymeOS_Patchrom/build/main.mk:470: warning: ignoring old recipe for target 'FMRadio.phone'

而后是合并Odex之后的错误：
OSError: [Errno 2] No such file or directory
/home/xiaohua/FlymeOS_Patchrom/build/newproject.mk:30: recipe for target 'out/oem_target_files.zip.std.zip' failed
make: *** [out/oem_target_files.zip.std.zip] Error 1

说明一下，这边官方ROM的FMRadio文件夹里是没有FMRadio.apk的。

望解决，十分感谢！

**Comment by imhansai** [comment]
没有就在makefile干掉

**Comment by ghost** [comment]
十分感谢！
