### ISSUE TITLE
{HELP}  booted but black screen.

### ISSUE THREAD

**Issue by sostk** [FlymeOS/manifest#19]
Hi i built flyme 6 for my device . The rom boots but at last only black screen is shown it doesnot show any thing in screen. But when I press the power buton the power menu shows up. Please help.

logcat:
[flyme6_2.txt](https://github.com/FlymeOS/manifest/files/1186821/flyme6_2.txt)

tombstones:
 [tombstones.zip](https://github.com/FlymeOS/manifest/files/1184829/tombstones.zip)
@hexiaoshuai  @zoujunhua

**Comment by hexiaoshuai** [comment]
https://github.com/FlymeOS/devices-base_cm/issues/12

**Comment by sostk** [comment]
what is it @hexiaoshuai ??

**Comment by hexiaoshuai** [comment]
Repeated questions

**Comment by sostk** [comment]
Its different ...I have changed the logcat first i have posted wrong one.

**Comment by sostk** [comment]
hi please can you open thisissue and help me ???

**Comment by hexiaoshuai** [comment]
https://github.com/FlymeOS/devices-base_cm/commit/e6bd4a4131c27e56a99667eb78882155fb1c9b56
The problem is the same as FlymeOS/devices-base_cm#12

**Comment by sostk** [comment]
please check the logcat again there is no such error in logcat.
