### ISSUE TITLE
依然是 flyme config 卡死

### ISSUE THREAD

**Issue by lihk11** [FlymeOS/manifest#22]
>>> config
>>> Check connecting state
>>> Check adb root state
>>> Wait for the device to be online...
>>> device is online
0 KB/s (5 bytes in 0.045s)

卡在这里就不动了

**Comment by hexiaoshuai** [comment]
这里需要一段时间的,快则几分钟慢则十几分钟,不想等强制退出手动放boot.img recovery.img 就行了

**Comment by lihk11** [comment]
其实是因为Check adb root state这一步过不去，而实际上设备是已经Root过了，所以我手动删掉了“check root state”的代码，就解决了这个问题。具体是什么原因，我也没有深入探究。
