### ISSUE TITLE
Fullota issue

### ISSUE THREAD

**Issue by rawmain** [FlymeOS/manifest#33]
[Makefile_copy.txt](https://github.com/FlymeOS/manifest/files/1561256/Makefile_copy.txt)

Source : CM-13.0 / Device : AMOI L861 (aka Stonex One / Santin Dante) - MT6795 - PowerVR G6200 - WQHD 2560x1440

Everything ok with config / newproject / patchall steps, but fullota returns KO : 
==
------------------------------------------------------
>>> apktool if(install framework): merged ...
I: Framework installed to: /root/.local/share/apktool/framework/1-merged_l861.apk
I: Framework installed to: /root/.local/share/apktool/framework/63-merged_l861.apk
I: Framework installed to: /root/.local/share/apktool/framework/2-merged_l861.apk
cp: cannot stat '/home/android/.local/share/apktool/framework//1-merged_l861.apk': No such file or directory
/home/android/flyme/build/main.mk:198: recipe for target 'out/obj/system/framework/ifmerged' failed
make[1]: *** [out/obj/system/framework/ifmerged] Error 1
make[1]: Leaving directory '/home/android/flyme/devices/l861'
/home/android/flyme/build/main.mk:34: recipe for target 'ota' failed
make: *** [ota] Error 2
------------------------------------------------------------------------

I've followed dev guides/instructions & even changed building machines/configurations (just in case to check packages/dependancies) without any different result.

I'm attaching current Makefile.
--------------------------------------------------
BASE := base_cm
DENSITY := xxxhdpi
RESOLUTION := 1440x2560

vendor_saved_apps := Bluetooth BluetoothMidiService CMSettingsProvider HTMLViewer KeyChain Nfc PicoTts PrintSpooler Stk UserDictionaryProvider BackupRestoreConfirmation DefaultContainerService ExternalStorageProvider FMRadio FusedLocation InputDevices ProxyHandler SharedStorageBackup Shell

vendor_modify_jars := framework services telephony-common wifi-service

board_saved_files := lib64/libwebviewchromium.so

board_modify_apps := SystemUI Telecom TeleService

override_property += \
    qemu.hw.mainkeys=1

override_property += \
    ro.flyme.romer=RawMain \
    ro.product.model_romer=L861_RawMain

PRODUCE_BLOCK_BASED_OTA := false

PRODUCE_INTERNATIONAL_ROM := true

**Comment by sky0hjh** [comment]
![pic](https://i.imgur.com/ueQl3Hm.png)
Open your Terminal,then
cd .local
mkdir -p share/apktool/framework
Maybe it will helps.

**Comment by rawmain** [comment]
Hello

Thanks. I've solved such issue (related to run in shell enviroment with root privileges) with this workaround = I've changed the definition of **APKTOOL_FRAME_PATH** in file **build/locals.mk** - line 105 : 

```
APKTOOL_FRAME_PATH := /root/.local/share/apktool/framework
# APKTOOL_FRAME_PATH := ~/.local/share/apktool/framework/
```
