### ISSUE TITLE
Newproject issue

### ISSUE THREAD

**Issue by mracar07** [FlymeOS/manifest#35]
Hello, I am building for Lenovo zuk z2pro(z2_row) with LOS14.1 was base,
flyme config

okey but

flyme newproject wont work.

https://hastebin.com/otesinigev.pl

**Comment by rawmain** [comment]
It seems a project work dir mismatch = it's decoding into a temporary dir /tmp/tmpYOLnB9/ , but next function expects to find file in another directory (_according to build/locals.mk default path definitions_).

If usage of /tmp/ folder is related to KO Write Permissions, perform a cleanall & run the build environment in a shell with root permissions.
