### ISSUE TITLE
ERR_USB_NOT_CONNECTED

### ISSUE THREAD

**Issue by ExperienceTesla** [FlymeOS/manifest#37]
when i do flyme config in 6.0 it works, but if i do this command in nougat 7.1 not work:
.>>> config
.>>> Check connecting state
.>>> Device is not found, Please connect device and pc with USB cable, and open Adb Debug in   device.

ERR_USB_NOT_CONNECTED: Can not find device
Please make sure your device has been connected.

<<< config failed

**Comment by p8tgames** [comment]
Same here

**Comment by qus1** [comment]
androidboot.selinux=permissive
+http://wangkeguan.com/?p=838

**Comment by ExperienceTesla** [comment]
thanks to qus1. just switch selinux mode from enforcing to permissive
