### ISSUE TITLE
flyme newproject build.prop problem

### ISSUE THREAD

**Issue by michal161** [FlymeOS/manifest#39]
how to fix this
`>>> normalize the out/oem_target_files.zip ...
D/reverse: Program args = []
I/reverse-zipformatter: unzip /home/michal161/Flyme/devices/j3xnlte/out/oem_target_files.zip to /tmp/tmpgBUUsD
D/reverse-zipformatter: 
Traceback (most recent call last):
  File "/home/michal161/Flyme/tools/otanormalize", line 38, in <module>
    ZipFormatter.create(OPTIONS).format()
  File "/home/michal161/Flyme/tools/reverses/zipformatter.py", line 84, in create
    zipType = zipModel.getZipType()
  File "/home/michal161/Flyme/tools/reverses/zipformatter.py", line 235, in getZipType
    raise Exception("Could not find %s, unknown ota type" %buildProp)
Exception: Could not find /tmp/tmpgBUUsD/system/build.prop, unknown ota type
/home/michal161/Flyme/build/newproject.mk:33: recipe for target 'out/oem_target_files.zip.std.zip' failed
make: *** [out/oem_target_files.zip.std.zip] Error 1`

**Comment by adeii** [comment]
My way - force ART type: replace line 84
zipType = zipModel.getZipType()
with
zipType = ZipModel.ART
and delete line 87 and lines 91 to 96.

**Comment by michal161** [comment]
and it worked?

**Comment by adeii** [comment]
Yes, on Flyme 5.1.2 (lollipop). Also change line 221 to:
zipType = ZipModel.ART
and delete lines 222 to 227 and 230 to 240.

**Comment by michal161** [comment]
k but will it work on nougat?

**Comment by adeii** [comment]
idk, it just forces script to set zipType to ART or Dalvik, evading bad reading of build.prop.

**Comment by michal161** [comment]
ty fixed but this has shown
IndenticalError: unexpected indent
/home/michal161/Flyme/build/newproject.mk:33: recipe for target 'out/oem_target_files.zip.std.zip' failed make: *** [out/oem_target_files.zip.std.zip] Error 1

**Comment by michal161** [comment]
https://pastebin.com/V2L5rmAX

**Comment by adeii** [comment]
I guess that line 88      deoat.OPTIONS = options 
can also be deleted...

**Comment by michal161** [comment]
`michal161@michal161-PC:~/Flyme/devices/j3xnlte$ flyme newproject
>>> newproject
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'out/obj/system/res/org.cyanogenmod.platform-res.remove'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'out/obj/system/res/org.cyanogenmod.platform-res.remove'
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'out/obj/system/app/org.cyanogenmod.platform-res.signed.apk'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'out/obj/system/app/org.cyanogenmod.platform-res.signed.apk'
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'clean-org.cyanogenmod.platform-res'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'clean-org.cyanogenmod.platform-res'
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'org.cyanogenmod.platform-res.phone'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'org.cyanogenmod.platform-res.phone'
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'out/obj/system/res/framework-res.remove'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'out/obj/system/res/framework-res.remove'
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'out/obj/system/app/framework-res.signed.apk'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'out/obj/system/app/framework-res.signed.apk'
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'clean-framework-res'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'clean-framework-res'
/home/michal161/Flyme/build/main.mk:470: warning: overriding recipe for target 'framework-res.phone'
/home/michal161/Flyme/build/main.mk:470: warning: ignoring old recipe for target 'framework-res.phone'
>>> unzip out/oem_target_files.zip.std.zip to vendor ...
<<< unzip out/oem_target_files.zip.std.zip to vendor done
<< prepare vendor done
* out ==> vendor
 
>> unpack /home/michal161/Flyme/devices/j3xnlte/boot.img to /home/michal161/Flyme/devices/j3xnlte/boot.img.out ...
Trying to unpack:
 Failed trying with SONY(Support boot.img of SONY 4.2+)
 Failed trying with MTK-V1(Support boot.img of MTK6752, MTK6732, MTK6595)
 Failed trying with MTK(Support boot.img of MTK 2.3~4.2)
 Succeed trying with QCOM(Support boot.img of QCOM 4.3+, especially for dt.img of QCOM) 
 
You might manually try unpacking with the remaining if QCOM does not actually work:
  COMMON-V1(Support boot.img of Android 4.3+)
  COMMON(Support boot.img of Android 2.3 ~ Android 4.2)

* Unpack QCOM /home/michal161/Flyme/devices/j3xnlte/boot.img --> out/obj/BOOT
<< unpack /home/michal161/Flyme/devices/j3xnlte/boot.img to /home/michal161/Flyme/devices/j3xnlte/boot.img.out done
>> unpack /home/michal161/Flyme/devices/j3xnlte/boot.img.out/RAMDISK/file_contexts.bin ...
converted success,outfile: /home/michal161/Flyme/devices/j3xnlte/boot.img.out/RAMDISK/file_contexts.
<< unpack /home/michal161/Flyme/devices/j3xnlte/boot.img.out/RAMDISK/file_contexts.bin done
>> prepare vendor recovery ...
<< prepare vendor recovery done
find: ‘vendor/system/framework’: No such file or directory
>>> decode  vendor/system/framework/framework-res.apk  /home/michal161/Flyme/devices/j3xnlte/framework-res ...
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
Input file (vendor/system/framework/framework-res.apk) was not found or was not readable.
/home/michal161/Flyme/build/newproject.mk:109: recipe for target '/home/michal161/Flyme/devices/j3xnlte/framework-res' failed
make: *** [/home/michal161/Flyme/devices/j3xnlte/framework-res] Error 162

ERR_APKTOOL_DECODE_FAILED: Failed to use apktool d xxx.apk.
Make sure the destination directory doesn't exist! 
And install framework resource first 
  $ ifdir xxx/system/framework

Example: 
If you want decode board's apk, you better install board's framework first! 
  $ ifdir board/system/framework

<<< newproject failed`
i have restored everything and changed only replaced zipType = zipModel.getZipType() with zipType = ZipModel.ART

**Comment by adeii** [comment]
No file vendor/system/framework/framework-res.apk is error. 
Copy it from ota.zip of phone to vendor/system/framework and maybe set as read-only (chmod 555)

**Comment by michal161** [comment]
Fixed
