### ISSUE TITLE
flyme config 卡死

### ISSUE THREAD

**Issue by coderstory** [FlymeOS/manifest#4]
====================================================
>>> Setup the Makefile Done!
Pull boot and recovery, It may take a few minutes, please wait....

卡在这里就没反应了，手机上未出现授权提示

手机是小米5  cm13.0最后一版  supersu2.79 root权限

ubuntu 17.04 系统   已经安装adb  并且能连接

**Comment by gesangtome** [comment]
你自己准备一份recovery.fstab和boot.img启动镜像  问题解决

**Comment by gesangtome** [comment]
你自己准备一份recovery.fstab和boot.img启动镜像  问题解决

**Comment by coderstory** [comment]
@gesangtome  活抓一只小灵剑
