### ISSUE TITLE
flyme config false in Mac

### ISSUE THREAD

**Issue by hands3dlabs** [FlymeOS/manifest#5]
exit_command: 1 file pushed. 0.0 MB/s (5 bytes in 0.003s)
>>> Root State: System Root
>>> Setup the Makefile Begin!
/Users/shionphan/www/others/android/project/tools/makeconfig: line 229: [: /var/folders/c8/r8gw60b94l1ct3xynpxyrhhh0000gn/T/-u.uUocmXEz: binary operator expected
>>> Get the files list in /system/framework failed! 
>>> Please check the adb is ok! 

////////

This is my adb devices
List of devices attached
064a39db0ac6d0da       device usb:336592896X product:hammerhead model:Nexus_5 device:hammerhead

**Comment by hexiaoshuai** [comment]
Mac is not supported yet
