### ISSUE TITLE
flyme newproject不能识别build.prop

### ISSUE THREAD

**Issue by qiurigao** [FlymeOS/manifest#7]
<< zip /home/flyme/flyme/devices/vivo-y55/out/oem_target_files.zip from /home/flyme/flyme/devices/vivo-y55/out/oem_target_files done
<<< generate vendor target files done
>>> normalize the out/oem_target_files.zip ...
D/reverse: Program args = []
I/reverse-zipformatter: unzip /home/flyme/flyme/devices/vivo-y55/out/oem_target_files.zip to /tmp/tmpl6va2K
D/reverse-zipformatter: 
Traceback (most recent call last):
  File "/home/flyme/flyme/tools/otanormalize", line 38, in <module>
    ZipFormatter.create(OPTIONS).format()
  File "/home/flyme/flyme/tools/reverses/zipformatter.py", line 84, in create
    zipType = zipModel.getZipType()
  File "/home/flyme/flyme/tools/reverses/zipformatter.py", line 235, in getZipType
    raise Exception("Could not find %s, unknown ota type" %buildProp)
Exception: Could not find /tmp/tmpl6va2K/system/build.prop, unknown ota type
/home/flyme/flyme/build/newproject.mk:30: recipe for target 'out/oem_target_files.zip.std.zip' failed
make: *** [out/oem_target_files.zip.std.zip] Error 1

<<< newproject failed

**Comment by hexiaoshuai** [comment]
请提供newproject完整log

**Comment by qiurigao** [comment]
生成ota包，刷进后5秒钟无限重启，抓不到logcat，好像是selinux二进制问题。是不是工具问题啊

发自我的vivo智能手机

**Comment by hexiaoshuai** [comment]
你的问题是无法newproject,我想得到的是newproject的打印输出
